definitions:
  models.BookingRes:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      hra_id:
        type: string
      id:
        type: string
      is_canceled:
        type: boolean
      number_of_people:
        type: integer
      reason:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
      will_arrive:
        type: string
      will_leave:
        type: string
    type: object
  models.CreateBookingReq:
    properties:
      hra_id:
        type: string
      is_canceled:
        type: boolean
      number_of_people:
        type: integer
      reason:
        type: string
      user_id:
        type: string
      will_arrive:
        type: string
      will_leave:
        type: string
    type: object
  models.Error:
    properties:
      message:
        type: string
    type: object
  models.GetAllByHRAIdRes:
    properties:
      user_id:
        items:
          $ref: '#/definitions/models.UserId'
        type: array
    type: object
  models.GetAllByUIdRes:
    properties:
      bookings:
        items:
          $ref: '#/definitions/models.BookingRes'
        type: array
    type: object
  models.List:
    properties:
      bookings:
        items:
          $ref: '#/definitions/models.BookingRes'
        type: array
    type: object
  models.StandartError:
    properties:
      error:
        $ref: '#/definitions/models.Error'
    type: object
  models.UpdateBookingReq:
    properties:
      hra_id:
        type: string
      id:
        type: string
      is_canceled:
        type: boolean
      number_of_people:
        type: integer
      reason:
        type: string
      user_id:
        type: string
      will_arrive:
        type: string
      will_leave:
        type: string
    type: object
  models.UserId:
    properties:
      id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: welcome to Booking API
  version: "1.7"
paths:
  /v1/booking/create/attraction:
    post:
      consumes:
      - application/json
      description: Api for Create Attraction Booking
      parameters:
      - description: createModel
        in: body
        name: CreateBookingReq
        required: true
        schema:
          $ref: '#/definitions/models.CreateBookingReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BookingRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Create Attraction Booking
      tags:
      - BOOKING_ATTRACTION
  /v1/booking/create/hotel:
    post:
      consumes:
      - application/json
      description: Api for Create Hotel Booking
      parameters:
      - description: createModel
        in: body
        name: CreateBookingReq
        required: true
        schema:
          $ref: '#/definitions/models.CreateBookingReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BookingRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Create Hotel Booking
      tags:
      - BOOKING_HOTEL
  /v1/booking/create/restaurant:
    post:
      consumes:
      - application/json
      description: Api for Create Restaurant Booking
      parameters:
      - description: createModel
        in: body
        name: CreateBookingReq
        required: true
        schema:
          $ref: '#/definitions/models.CreateBookingReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BookingRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Create Restaurant Booking
      tags:
      - BOOKING_RESTAURANT
  /v1/booking/delete/attraction/{id}:
    delete:
      consumes:
      - application/json
      description: Api for Delete Attraction
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StandartError'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Delete Attraction
      tags:
      - BOOKING_ATTRACTION
  /v1/booking/delete/hotel/{id}:
    delete:
      consumes:
      - application/json
      description: Api for Delete Hotel
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StandartError'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Delete Hotel
      tags:
      - BOOKING_HOTEL
  /v1/booking/delete/restaurant/{id}:
    delete:
      consumes:
      - application/json
      description: Api for Delete Restaurant
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StandartError'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Delete Restaurant
      tags:
      - BOOKING_RESTAURANT
  /v1/booking/get/attractions/by/user/{id}:
    get:
      consumes:
      - application/json
      description: Api for Get All Attractions By User Id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetAllByUIdRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Get All Attractions By User Id
      tags:
      - BOOKING_ATTRACTION
  /v1/booking/get/hotels/by/user/{id}:
    get:
      consumes:
      - application/json
      description: Api for Get All Hotels By User Id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetAllByUIdRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Get All Hotels By User Id
      tags:
      - BOOKING_HOTEL
  /v1/booking/get/restaurants/by/user/{id}:
    get:
      consumes:
      - application/json
      description: Api for Get All Restaurants By User Id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetAllByUIdRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Get All Restaurants By User Id
      tags:
      - BOOKING_RESTAURANT
  /v1/booking/get/users/by/attraction/{id}:
    get:
      consumes:
      - application/json
      description: Api for Get All Users By Attraction Id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetAllByHRAIdRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Get All Users By Attraction Id
      tags:
      - BOOKING_ATTRACTION
  /v1/booking/get/users/by/restaurant/{id}:
    get:
      consumes:
      - application/json
      description: Api for Get All Users By Restaurant Id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetAllByHRAIdRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Get All Users By Restaurant Id
      tags:
      - BOOKING_RESTAURANT
  /v1/booking/get/users/by/room/{id}:
    get:
      consumes:
      - application/json
      description: Api for Get All Users By Room Id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetAllByHRAIdRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Get All Users By Room Id
      tags:
      - BOOKING_HOTEL
  /v1/booking/list/attractions:
    get:
      consumes:
      - application/json
      description: Api for List Attractions
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.List'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: List Attractions
      tags:
      - BOOKING_ATTRACTION
  /v1/booking/list/deleted/attractions:
    get:
      consumes:
      - application/json
      description: Api for List Deleted Attractions
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.List'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: List Deleted Attractions
      tags:
      - BOOKING_ATTRACTION
  /v1/booking/list/deleted/hotels:
    get:
      consumes:
      - application/json
      description: Api for List Deleted Hotels
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.List'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: List Deleted Hotels
      tags:
      - BOOKING_HOTEL
  /v1/booking/list/deleted/restaurants:
    get:
      consumes:
      - application/json
      description: Api for List Deleted Restaurants
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.List'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: List Deleted Restaurants
      tags:
      - BOOKING_RESTAURANT
  /v1/booking/list/hotels:
    get:
      consumes:
      - application/json
      description: Api for List Hotels
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.List'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: List Hotels
      tags:
      - BOOKING_HOTEL
  /v1/booking/list/restaurants:
    get:
      consumes:
      - application/json
      description: Api for List Restaurants
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.List'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: List Restaurants
      tags:
      - BOOKING_RESTAURANT
  /v1/booking/update/booked/attraction:
    put:
      consumes:
      - application/json
      description: Api for Update Booked Attraction
      parameters:
      - description: createModel
        in: body
        name: models.UpdateBookingReq
        required: true
        schema:
          $ref: '#/definitions/models.UpdateBookingReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BookingRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Update Booked Attraction
      tags:
      - BOOKING_ATTRACTION
  /v1/booking/update/booked/hotel:
    put:
      consumes:
      - application/json
      description: Api for Update Booked Hotel
      parameters:
      - description: createModel
        in: body
        name: models.UpdateBookingReq
        required: true
        schema:
          $ref: '#/definitions/models.UpdateBookingReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BookingRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Update Booked Hotel
      tags:
      - BOOKING_HOTEL
  /v1/booking/update/booked/restaurant:
    put:
      consumes:
      - application/json
      description: Api for Update Booked Restaurant
      parameters:
      - description: createModel
        in: body
        name: models.UpdateBookingReq
        required: true
        schema:
          $ref: '#/definitions/models.UpdateBookingReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BookingRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      security:
      - ApiKeyAuth: []
      summary: Update Booked Restaurant
      tags:
      - BOOKING_RESTAURANT
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
