definitions:
  models.AttractionModel:
    properties:
      attraction_id:
        type: string
      attraction_name:
        type: string
      contact_number:
        type: string
      created_at:
        type: string
      description:
        type: string
      images:
        items:
          $ref: '#/definitions/models.ImageModel'
        type: array
      licence_url:
        type: string
      location:
        $ref: '#/definitions/models.LocationModel'
      owner_id:
        type: string
      rating:
        type: number
      updated_at:
        type: string
      website_url:
        type: string
    type: object
  models.CreateAttraction:
    properties:
      attraction_name:
        default: Anhor Park
        type: string
      contact_number:
        default: +(99891)-234-56-78
        type: string
      description:
        default: available for all ages
        type: string
      images:
        items:
          $ref: '#/definitions/models.CreateImage'
        type: array
      licence_url:
        default: https://creativecommons.org/licenses/by/4.0/
        type: string
      location:
        $ref: '#/definitions/models.CreateLocation'
      rating:
        default: 4.3
        type: number
      website_url:
        default: https://creativecommons.org/licenses/by/4.1/
        type: string
    type: object
  models.CreateImage:
    properties:
      image_url:
        default: www.photo/images/141
        type: string
    type: object
  models.CreateLocation:
    properties:
      address:
        default: 87G9+V57, Shaykhontohur Street 28, Tashkent, Toshkent Shahri
        type: string
      city:
        default: Tashkent
        type: string
      country:
        default: Uzbekistan
        type: string
      latitude:
        default: 40.7128
        type: number
      longitude:
        default: 74.006
        type: number
      state_province:
        default: Shaykhontohur
        type: string
    type: object
  models.Error:
    properties:
      message:
        type: string
    type: object
  models.ImageModel:
    properties:
      created_at:
        type: string
      establishment_id:
        type: string
      image_id:
        type: string
      image_url:
        type: string
      updated_at:
        type: string
    type: object
  models.LocationModel:
    properties:
      address:
        type: string
      city:
        type: string
      country:
        type: string
      created_at:
        type: string
      establishment_id:
        type: string
      latitude:
        type: number
      location_id:
        type: string
      longitude:
        type: number
      state_province:
        type: string
      updated_at:
        type: string
    type: object
  models.StandartError:
    properties:
      error:
        $ref: '#/definitions/models.Error'
    type: object
info:
  contact: {}
paths:
  /v1/attraction/create:
    post:
      consumes:
      - application/json
      description: Api for creating attraction
      parameters:
      - description: Attraction
        in: body
        name: Attraction
        required: true
        schema:
          $ref: '#/definitions/models.CreateAttraction'
      - description: owner_id
        in: query
        name: owner_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AttractionModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.StandartError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandartError'
      summary: CREATE ATTRACTION
      tags:
      - ATTRACTION
swagger: "2.0"
